name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main  # atau cabang utama kamu

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: turnkey-chimera-460001-p0
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker to use gcloud as a credential helper
        run: gcloud auth configure-docker

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/turnkey-chimera-460001-p0/freshguard-image .
          docker push gcr.io/turnkey-chimera-460001-p0/freshguard-image

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy freshguard-app \
            --image gcr.io/turnkey-chimera-460001-p0/freshguard-image \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars=SECRET_KEY=ini_secret_key_rahasia,MYSQL_USER=root,MYSQL_PASSWORD=,MYSQL_DB=freshguard,MYSQL_UNIX_SOCKET=/cloudsql/turnkey-chimera-460001-p0:us-central1:freshguard-uas,MAIL_SERVER=smtp.gmail.com,MAIL_PORT=587,MAIL_USE_TLS=True,MAIL_USE_SSL=False,MAIL_USERNAME=heydisisme222@gmail.com,MAIL_PASSWORD=cmssqjgxwjnulzhu,MAIL_DEFAULT_SENDER=heydisisme222@gmail.com
