name: Deploy to Cloud Run

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Docker
      uses: docker/setup-buildx-action@v2

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Build and Push Image
      run: |
        docker build --no-cache -t gcr.io/turnkey-chimera-460001-p0/freshguard-image:${{ github.sha }} .
        docker push gcr.io/turnkey-chimera-460001-p0/freshguard-image:${{ github.sha }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy freshguard-app \
          --image gcr.io/turnkey-chimera-460001-p0/freshguard-image:${{ github.sha }} \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated